# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ana', ['core', 'point-to-point', 'csma', 'internet', 'applications', 'mytrace'])
    module.source = [
        'model/ana-sender.cc',
        'model/ana-receiver.cc',
        'model/ana-packet-tag.cc',
        'helper/ana-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ana')
    module_test.source = [
        'test/ana-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/ana-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'ana'
    headers.source = [
        'model/ana-sender.h',
        'model/ana-receiver.h',
        'model/ana-packet-tag.h',
        'helper/ana-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

