# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    ana = bld.create_ns3_program('ana-example', ['ana'])
    ana.source = 'ana-example.cc'
    gcc_tcp = bld.create_ns3_program('gcc_tcp',
                                     ['core','razor-ns3','internet','network','point-to-point', 'applications','traffic-control','mytrace'])
    gcc_tcp.source = 'gcc_tcp.cc'

